### ISSUE TITLE
PPO, SPPO and ILQL

### ISSUE THREAD

**Issue by OliviaViessmann** [microsoft/RLHF-APA#9]
Hi,
thank you for uploading your training code to git. Could you add a sentence in the Readme to clarify the difference between the model names on the repo (PPO,SPPO and ILQL) and int he paper? Which one refers to the standard PPO (SPPO?) and the AWR?
Thanks a lot
Olivia

**Comment by BZ-MSFT** [comment]
Hi Olivia,

Thanks for the feedback and sorry for the confusion. Indeed, the original SPPO file name refers to the code of both APA and AWR. We have changed the file names to APA to avoid confusion in our most recent PR. 

Best,
Banghua
